version: 2
jobs:
  test-all:
    docker:
      - image: sudachen/go-ml-ci

    parallelism: 1

    environment:
      MXNET_ENFORCE_DETERMINISM: 1
      OMP_NUM_THREADS: 4
      MXNET_OMP_MAX_THREADS: 4
      CC_TEST_REPORTER_ID: b021cbc593e35d6998c4da0221c16c55b679073d46dc660a5928c405a561841f

    steps:
      - run: |
          # Use HTTPS for public repos to avoid SSH key issues
          git config --global url."https://github.com/".insteadOf "git@github.com:"
      
      - checkout

      - restore_cache:
          # https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run: make build

      - run: make run-tests

      - run: /usr/local/bin/cc-test-reporter after-build -t gocov

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-all
